---
title: "Week 13 HW"
author: "Kaitlyn Alley"
date: "2025-04-13"
output: html_document
---


```{r}
library(ggplot2)
library(dplyr)
library(ggrepel)
```
```{r}
ggplot(iris,aes(Petal.Length,Petal.Width,size = Petal.Width,color=Species))+geom_point(alpha=0.7) +
  scale_size_continuous(range = c(1, 4)) +
  labs(title = "Sepal vs Petal Length by Species",
       subtitle = "Point size represents Sepal Width")+
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5
        ))

```
```{r}
ggplot(mtcars, aes(hp,mpg, label = rownames(mtcars),color=wt)) +
  geom_point(size = 2) +
  geom_text_repel(size = 3, max.overlaps = 50) +
  scale_color_gradient(low = "green", high = "red") +
  labs(title = "MPG vs Horsepower",
       subtitle = "Color by Weight, Labeled Car Name",
       x = "Horsepower", y = "Miles per Gallon")+
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "darkgrey"),
        panel.grid.minor = element_line(color = "lightgrey"),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
    )+
  annotate("rect", xmin = 250, xmax = 350, ymin = 25, ymax = 35, fill = "blue", alpha = 0.3) +
  annotate("text", x = 300, y = 30, label = "High HP and High MPG", size = 4, color = "black")
```


```{r}
ggplot(diamonds, aes(x = carat)) +
  geom_histogram(bins = 50, fill = "steelblue") +
  facet_wrap(~ cut) +
  scale_x_continuous(limits = c(0, 3)) +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(hjust = 1)
  ) +
  labs(
    title = "Carat Distribution by Cut"
  )
```


```{r}
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species, size = Petal.Length)) +
  geom_point()+
  scale_size_continuous(range = c(1, 6), breaks = c(1,3, 5)) +
  theme(legend.position = "bottom") +
  ggtitle("Sepal Dimensions")+
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)
        ) +
  theme_classic()+
  scale_x_continuous(limits = c(4, 8)) +
  scale_y_continuous(limits = c(2, 4.5))
```

```{r}
ggplot(ToothGrowth, aes(dose,len,fill=supp)) +
  geom_bar(stat = "summary", fun = "mean",position = "dodge") +
  scale_x_continuous(breaks = c(0.5, 1, 1.5)) +
  labs(x = "Dose", y = "Mean Length",title = "Average Tooth Length by Supplement and Dose")+
  theme_classic()
```

```{r}
ggplot(ChickWeight,aes(Time,weight))+geom_point()+
  geom_smooth()
```


```{r}

ggplot(airquality, aes(x = Temp, y = Ozone)) +
  geom_point(aes(color = Solar.R)) +
  scale_color_gradient(low = "lightpink", high = "lightblue")+
  geom_smooth(color = "blue")+
  theme_classic()
```


```{r}
library(RColorBrewer)


ggplot(HairEyeColor,aes(hair,freq))+geom_point()
```

```{r}
mean_temp <- airquality %>%
  group_by(Month) %>%
  summarise(Mean_Temp = mean(Temp, na.rm = TRUE))

ggplot(mean_temp, aes(x = factor(Month), y = Mean_Temp)) +
  geom_segment(aes(xend = lead(factor(Month)), yend = lead(Mean_Temp)))+ 
  labs(x = "Month", y = "Mean temperature", 
       title = "Mean Daily Temp in NY (May-Sept)") +
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5)
        )
```

```{r}
avg_hp <- mtcars %>%
  group_by(gear) %>%
  summarise(avg_hp = mean(hp))

ggplot(avg_hp, aes(x = factor(gear), y = avg_hp)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x="Gear", y="Mean hp", title = "Average HP by Gear") +
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5)
        )
```



